{
  "swagger": "3.0",
  "info": {
    "title": "Crosswork Data Gateway Manager Troubleshooting APIs",
    "description": "APIs to support CDG troubleshooting",
    "contact": {
      "name": "Crosswork Team, Cisco",
      "email": "support@cisco.com"
    },
    "license": {
      "name": "Cisco Software License Agreement",
      "url": "http://www.cisco.com/public/sw-license-agreement.html"
    },
    "version": "1.0.0"
  },
  "basePath": "/crosswork/dg-manager",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/command/showtech": {
      "post": {
        "summary": "Submits showtech command to collect CDG showtech logs",
        "operationId": "SubmitShowtechCommand",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json "
        ],
        "parameters": [{
          "name": "Body",
          "in": "body",
          "required": true,
          "description": "",
          "schema": {
            "$ref": "#/definitions/SubmitShowtechCommand"
          }
        }],
        "responses": {
          "200": {
            "description": "OK. The showtech log collection command got submitted. Use /v1/command/query to find out the status."
          },
          "400": {
            "description": "Bad Request. The request is malformed in some way and the server cannot process it.",
            "headers": {}
          }
        }
      }
    },
    "/v1/command/reboot": {
      "post": {
        "summary": "Submits reboot command to reboot CDG. Crosswork user with read, write privileges can submit reboot command.",
        "operationId": "SubmitRebootCommand",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json "
        ],
        "parameters": [{
          "name": "Body",
          "in": "body",
          "required": true,
          "description": "",
          "schema": {
            "$ref": "#/definitions/SubmitRebootCommand"
          }
        }],
        "responses": {
          "200": {
            "description": "OK. The reboot data gateway command got submitted. Check the operational status of Data Gateway to determine it got rebooted.",
            "headers": {}
          },
          "400": {
            "description": "Bad Request. The request is malformed in some way and the server cannot process it."
          }
        }
      }
    },
    "/v1/command/query": {
      "post": {
        "summary": "Gets CDG Showtech log collection status",
        "operationId": "ShowtechStatusRequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [{
          "name": "Body",
          "in": "body",
          "required": true,
          "description": "",
          "schema": {
            "$ref": "#/definitions/ShowtechStatusRequest"
          }
        }],
        "responses": {
          "200": {
            "description": "OK. The request was successful. The status is contained in the response body. Once the data gateway showtech log collection is successful. The response contains the downloadable link of the showtech log file. ",
            "headers": {}
          }
        }
      }
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [{
    "bearerAuth": []
  }],
  "definitions": {
    "SubmitShowtechCommand": {
      "title": "ShowtechCommandPayload",
      "example": {
        "id": "5065",
        "commandName": "SHOW_TECH_SUPPORT",
        "clientId": {
          "uuid": "d58de587-5da2-4a62-b010-32395acc8dbc"
        },
        "args": [{
          "key": "passphrase",
          "value": {
            "str": "test1234"
          }
        }]
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "commandName": {
          "type": "string"
        },
        "clientId": {
          "$ref": "#/definitions/ClientId"
        },
        "args": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Arg"
          }
        }
      },
      "required": [
        "id",
        "commandName",
        "clientId",
        "args"
      ]
    },
    "ClientId": {
      "title": "ClientId",
      "example": {
        "uuid": "d58de587-5da2-4a62-b010-32395acc8dbc"
      },
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    },
    "Arg": {
      "title": "Arg",
      "example": {
        "key": "passphrase",
        "value": {
          "str": "test1234"
        }
      },
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/Value"
        }
      },
      "required": [
        "key",
        "value"
      ]
    },
    "Value": {
      "title": "Value",
      "example": {
        "str": "test1234"
      },
      "type": "object",
      "properties": {
        "str": {
          "type": "string"
        }
      },
      "required": [
        "str"
      ]
    },
    "SubmitRebootCommand": {
      "title": "RebootCommandPayload",
      "example": {
        "id": "3003",
        "commandName": "REBOOT_VM",
        "clientId": {
          "uuid": "c9582aba-456c-43b7-aab0-605e28c6f131"
        }
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "commandName": {
          "type": "string"
        },
        "clientId": {
          "$ref": "#/definitions/ClientId"
        }
      },
      "required": [
        "id",
        "commandName",
        "clientId"
      ]
    },
    "ShowtechStatusRequest": {
      "title": "ShowtechStatusRequest",
      "example": {
        "queryParams": [{
          "field": "CMDID",
          "value": {
            "valueStr": "5065"
          }
        }]
      },
      "type": "object",
      "properties": {
        "queryParams": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/QueryParam"
          }
        }
      },
      "required": [
        "queryParams"
      ]
    },
    "QueryParam": {
      "title": "QueryParam",
      "example": {
        "field": "CMDID",
        "value": {
          "valueStr": "5065"
        }
      },
      "type": "object",
      "properties": {
        "field": {
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/Value1"
        }
      },
      "required": [
        "field",
        "value"
      ]
    },
    "Value1": {
      "title": "Value1",
      "example": {
        "valueStr": "5065"
      },
      "type": "object",
      "properties": {
        "valueStr": {
          "type": "string"
        }
      },
      "required": [
        "valueStr"
      ]
    }
  }
}